baseURL: "https://ramanebrahimi.github.io/" 
title: Raman Ebrahimi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - identifier: "papers"
          name: "Papers"
          url: "/papers/"
          weight: 10
        - identifier: "courses"
          name: "Teaching"
          url: "/courses/"
          weight: 20
        - identifier: "data"
          name: "Data"
          url: "/data/"
          weight: 30
        - identifier: "cv"
          name: "CV"
          url: "/cv.pdf"
          weight: 40
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "Hello! This is Raman. I'm a Ph.D. student in Machine Learning and Data Science at the University of California San Diego. My research focuses on the intersection of Network Science, Game Theory, and Optimization, specifically investigating socio-technical systems through mathematical modeling and computational techniques."
    author: Raman Ebrahimi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","courses","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Raman Ebrahimi
          subtitle: "I am a Ph.D. student in Machine Learning and Data Science at the University of California San Diego, advised by [Dr. Massimo Franceschetti](http://web.eng.ucsd.edu/~massimo/Home.html). My research interests are in behavioral game theory, optimization, and network science.<br><br> I develop game-theoretic frameworks and AI/ML models that incorporate cognitive biases, using mathematical optimization and Python simulations. I analyze Nash equilibrium conditions in multilayer network games to derive policy insights from real-world data and design interactive strategy games to study human-environment interactions.<br><br> Currently, as a Founding Quantitative Researcher at MarketCrunch AI, I research and enhance predictive models for stocks and market indicators, and develop algorithmic trading strategies. My work involves leveraging mathematical and statistical techniques, conducting exploratory data analysis, and optimizing prediction pipelines.<br><br> My goal is to solve complex real-world problems by bridging theoretical modeling with cutting-edge computational and quantitative methods.<br><br><b>Previously:</b><br><br><ul><li><b>Data Science Intern at HCM Tradeseal (Ongoing):</b> I am currently designing a pricing and decision assistant search engine. My responsibilities include optimizing Python ETL pipelines to ensure data integrity, building data validation frameworks, and automating data quality workflows. I apply NLP and statistical modeling to enhance parsing logic for unstructured data, contributing to a searchable database of over 450,000 data points.</li><li><b>Data Analyst Intern at the American Institute for Behavioral Research and Technology (AIBRT):</b> I revived a legacy Python/SQL-based graphing application for the 'Generativity Theory' project. This involved integrating machine learning models (PyTorch, scikit-learn) for user-agnostic behavior prediction, achieving over 90% accuracy in select modes, and enhancing the models through mathematical optimization techniques.</li><li><b>Data Science Product Manager at the Scientific Association of Industrial Engineering:</b> I led a team of computer science students in the development of a real-time strategy game in Unity. My role included overseeing risk management, designing the in-game economy, performing market predictions, and running simulations to test server integrity and identify potential exploits.</li></ul>"
        
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Projects
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:raman@ucsd.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=88OyKqwAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/RamanEbrahimi
        - name: LinkedIn
          url: https://www.linkedin.com/in/ramanebrahimi/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Raman Ebrahimi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
